language: python

python:
  - '2.7'

before_install:
  - git clone -b unstable https://github.com/dpmtools/dpm
  - sudo dpm/install -i
  - sudo dpm/install -b
  - sudo dpm/install -r
  - sudo dpm/install -m
  - sudo dpm/install

install:
  - sudo ./install

services:
  - mongodb

before_script:
  - sleep 5
  - sudo dpm/bin/dpm-start &
  - sleep 20
  - sudo bin/dpmtest-server &
  - sleep 5

script:
  - sudo bin/dpmtest-client &
  - sleep 20

dist:
  - xenial
